// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8c-HGEIDnRqjKzqEG3SMB_QlwTMniVDI',
    appId: '1:1024425298006:web:b914a8a30dee85e6a4d3f7',
    messagingSenderId: '1024425298006',
    projectId: 'travel-a61f2',
    authDomain: 'travel-a61f2.firebaseapp.com',
    storageBucket: 'travel-a61f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc1XIw4UiEmUnkdo_0u6_ueNHz-jDlsfs',
    appId: '1:1024425298006:android:c6ab469aaf06f948a4d3f7',
    messagingSenderId: '1024425298006',
    projectId: 'travel-a61f2',
    storageBucket: 'travel-a61f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0SCoJI4-ExVARFEchr6ZtGsJmip0FA8c',
    appId: '1:1024425298006:ios:bf8adc035dde233ca4d3f7',
    messagingSenderId: '1024425298006',
    projectId: 'travel-a61f2',
    storageBucket: 'travel-a61f2.appspot.com',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0SCoJI4-ExVARFEchr6ZtGsJmip0FA8c',
    appId: '1:1024425298006:ios:bf8adc035dde233ca4d3f7',
    messagingSenderId: '1024425298006',
    projectId: 'travel-a61f2',
    storageBucket: 'travel-a61f2.appspot.com',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8c-HGEIDnRqjKzqEG3SMB_QlwTMniVDI',
    appId: '1:1024425298006:web:0ea7674db66e5a52a4d3f7',
    messagingSenderId: '1024425298006',
    projectId: 'travel-a61f2',
    authDomain: 'travel-a61f2.firebaseapp.com',
    storageBucket: 'travel-a61f2.appspot.com',
  );
}
